Implement camera
DIT112-V21/group-14 pull request #43
Opened 2021-05-04 19:22 UTC by VladLiteanu

Encode and display a camera view to the UI.
Increased camera resolution and framerate. 
Related Issues: #33

2021-05-04 23:47 UTC, EnisBourbia requested changes

2021-05-04 23:53 UTC, VladLiteanu commented on front_end/connect-to-car.html
> +  <canvas id="backup-camera" width="640" height="480"></canvas></canvas>
I missed that one 👍

2021-05-05 00:01 UTC, EnisBourbia commented on front_end/connect-to-car.html
> +  <canvas id="backup-camera" width="640" height="480"></canvas></canvas>
Looks great now! Well done :)

2021-05-05 00:02 UTC, EnisBourbia approved these changes

2021-05-05 00:03 UTC, merged